---
jobs:
- name: deploy
  serial: true
  plan:
  - in_parallel:
    - get: docs
      trigger: true
    - get: web
      trigger: true
  - task: build-docs
    file: docs/ci/tasks/build.yml
    params:
      GOOGLE_ANALYTICS_KEY: ((google_analytics_key))
  - task: push
    tags: [nimbus]
    file: web/ci/tasks/push.yml
    params:
      CF_API: ((cf_api))
      CF_USERNAME: ((cf_user.username))
      CF_PASSWORD: ((cf_user.password))
      CF_ORGANIZATION: ((cf_organization))
      CF_SPACE: ((cf_space))
      WEB_CONFIG: ((web_config))
      PRIVATE_KEY: ((bosh-io-cloudfront-signing-key.private_key))
- name: pull-data
  serial: true
  plan:
  - in_parallel:
    - get: web
    - get: data-reload-interval
      trigger: true
    - get: releases-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-core-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-cpi-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-legacy-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-softlayer-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-alicloud-index
      trigger: true
      params:
        depth: 1
    - get: stemcells-windows-index
      trigger: true
      params:
        depth: 1
    - get: bosh-io-web-docker-image
  - task: pull-data
    tags: [nimbus]
    file: web/ci/tasks/pull-data.yml
    image: bosh-io-web-docker-image
    params:
      CF_API: ((cf_api))
      CF_USERNAME: ((cf_user.username))
      CF_PASSWORD: ((cf_user.password))
      CF_ORGANIZATION: ((cf_organization))
      CF_SPACE: ((cf_space))
resources:
- name: web
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-web.git
- name: docs
  type: git
  source:
    uri: https://github.com/cloudfoundry/docs-bosh.git
- name: bosh-io-web-docker-image
  type: registry-image
  source:
    repository: bosh/bosh-io-web
    tag: default
    username: ((docker.username))
    password: ((docker.password))
- name: data-reload-interval
  type: time
  source:
    interval: 1h
- name: releases-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-releases-index.git
- name: stemcells-core-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-stemcells-core-index.git
- name: stemcells-cpi-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-stemcells-cpi-index.git
- name: stemcells-legacy-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-stemcells-legacy-index.git
- name: stemcells-softlayer-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-stemcells-softlayer-index.git
- name: stemcells-alicloud-index
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/stemcells-alicloud-index.git
- name: stemcells-windows-index
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-io-stemcells-windows-index.git
